# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
#   pod 'SplineRuntime', :git => 'https://github.com/splinetool/spline-ios.git', :branch => 'main'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
